#!/usr/bin/env bash

# If you update this number make sure the graalvm.version value in ./pom.xml matches
VERSION="22.2.0"

MAIN_CLASS="com.vztekoverflow.bacil.launcher.BACILLauncher"
SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd -P)"

MACOS_CIL_PATH="--cil.libraryPath=/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.3"

function extractGraalVMVersion() {
    local -r releasePath="${1:?Path to relese file is a required parameter}"
    grep "GRAALVM_VERSION" "$releasePath" 2> /dev/null \
        | awk 'BEGIN {FS="="} {print $2}' \
        | sed 's/"//g' \
        | cut -d '.' -f 1-3
}

function versionCheck() {
    local -r message="${1:-Wrong GraalVM version.}"
    if [[ "$GRAALVM_VERSION" != "$VERSION" ]]; then
        fail "$message"
    fi
}

function fail() {
    local -r message="${1:-Unknown error}"
    local -r exitCode="${2:-1}"
    >&2 echo "$message"
    exit "$exitCode"
}

#######################################################################
# Locations of the language and launcher jars as well as the java command are
# different if I'm running from the repository or as a component in GraalVM
#######################################################################
GRAALVM_VERSION=$(extractGraalVMVersion "$SCRIPT_HOME/../release")
LANGUAGE_PATH="$SCRIPT_HOME/language/target/language-1.0-SNAPSHOT.jar"
LAUNCHER_PATH="$SCRIPT_HOME/launcher/target/bacil-launcher.jar"
# Check the GraalVM version in JAVA_HOME
if [[ "$JAVA_HOME" != "" ]]; then
    GRAALVM_VERSION=$(extractGraalVMVersion "$JAVA_HOME"/release)
    if [[ "$GRAALVM_VERSION" != "" ]]; then
        versionCheck "Wrong version of GraalVM in \$JAVA_HOME. Expected: $VERSION, found $GRAALVM_VERSION"
    fi
    JAVACMD=${JAVACMD:=$JAVA_HOME/bin/java}
    if [[ ! -f $LANGUAGE_PATH ]]; then
        fail "Could not find language on $LANGUAGE_PATH. Did you run mvn package?"
    fi
    if [[ ! -f $LAUNCHER_PATH ]]; then
        fail "Could not find launcher on $LAUNCHER_PATH. Did you run mvn package?"
    fi
else
    fail "JAVA_HOME is not set"
    exit 1
fi


#######################################################################
# Parse arguments, prepare Java command and execute
#######################################################################
if [[ "$GRAALVM_VERSION" != "" ]]; then
    PROGRAM_ARGS=()
    JAVA_ARGS=()

    # Hardcoded path for MacOS to speed up development.
    if [[ "$OSTYPE" == "darwin"* ]]; then
      PROGRAM_ARGS+=("$MACOS_CIL_PATH")
    fi

    for opt in "$@"
    do
      case $opt in
        -debug)
            JAVA_ARGS+=("-Xdebug" "-Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y") ;;
        -dump)
            JAVA_ARGS+=("-Dpolyglot.engine.AllowExperimentalOptions=true" "-Dgraal.Dump=Truffle:1" "-Dpolyglot.engine.BackgroundCompilation=false" "-Dpolyglot.engine.TraceCompilation=true" "-Dpolyglot.engine.TraceCompilationDetails=true") ;;
        -disassemble)
            JAVA_ARGS+=("-Dpolyglot.engine.AllowExperimentalOptions=true" "-XX:CompileCommand=print,*OptimizedCallTarget.profiledPERoot" "-XX:CompileCommand=exclude,*OptimizedCallTarget.profiledPERoot" "-Dpolyglot.engine.BackgroundCompilation=false" "-Dpolyglot.engine.TraceCompilation=true" "-Dpolyglot.engine.TraceCompilationDetails=true") ;;
        -J*)
            opt=${opt:2}
            JAVA_ARGS+=("$opt") ;;
        *)
            PROGRAM_ARGS+=("$opt") ;;
      esac
    done
    "$JAVACMD" "${JAVA_ARGS[@]}" -Dtruffle.class.path.append="$LANGUAGE_PATH" -cp "$LAUNCHER_PATH" "$MAIN_CLASS" "${PROGRAM_ARGS[@]}"
else
    echo "Warning: Could not find GraalVM on $JAVA_HOME. Running on JDK without support for compilation."
    echo
    PROGRAM_ARGS=()
    JAVA_ARGS=()

    # Hardcoded path for MacOS to speed up development.
    if [[ "$OSTYPE" == "darwin"* ]]; then
      PROGRAM_ARGS+=("$MACOS_CIL_PATH")
    fi

    for opt in "$@"
    do
      case $opt in
        -debug)
            JAVA_ARGS+=("-Xdebug" "-Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y") ;;
        -dump)
            echo "NOTE: Ignoring -dump, only supported on GraalVM." ;;
        -disassemble)
            echo "NOTE: Ignoring -disassemble" ;;
        -J*)
            opt=${opt:2}
            JAVA_ARGS+=("$opt") ;;
        *)
            PROGRAM_ARGS+=("$opt") ;;
      esac
    done
    if [[ ! -d $HOME/.m2 ]]; then
        echo "Could not find mvn cache at $HOME/.m2"
        exit 1
    fi
    GRAAL_SDK_PATH="$HOME/.m2/repository/org/graalvm/sdk/graal-sdk/$VERSION/graal-sdk-$VERSION.jar"
    TRUFFLE_API_PATH="$HOME/.m2/repository/org/graalvm/truffle/truffle-api/$VERSION/truffle-api-$VERSION.jar"
    "$JAVACMD" "${JAVA_ARGS[@]}" -cp "$GRAAL_SDK_PATH":"$LAUNCHER_PATH":"$LANGUAGE_PATH":"$TRUFFLE_API_PATH" "$MAIN_CLASS" "${PROGRAM_ARGS[@]}"
fi